version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: install pipenv
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          name: codecheck
          command: |
            pipenv run python sample.py
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
